version: "3.9"

services:
  novnc:
    build: ./novnc/
    restart: always
    ports:
      - "80:6900"
    networks:
      - net
      - isolated1
      - isolated2
      - isolated3

  xvnc1:
    build: ./ubuntu_icewm/
    environment:
      - USER=isen
      - VNC_PORT=5900
      - VNC_PASSWD=vncpassword
      - IS_SECURE=true
    depends_on:
      - novnc
    networks:
      - isolated1
    cap_add:
      - LINUX_IMMUTABLE


networks:
  isolated1:
    internal: true
  isolated2:
    internal: true
  isolated3:
    internal: true
  net:
    #external: true # Set it to true if you can't communicate with NoVNC
