version: "3.9"

# Utiliser le nom du service pour le host à chaque fois

services:
  novnc:
    build: ./novnc/
    restart: always # à mettre sur les xvnc aussi si on veut un redémarrage auto
    ports: # port 80 exposé à l'extérieur pour accéder au port novnc
      - "80:6900"
    networks:
      - net
      - isolated1
      - isolated2
      - isolated3

  xvnc1:
    build: ./ubuntu_icewm/ # emplacement du dockerfile correspondant
    environment:
      - USER=isen
      - VNC_PORT=5900
      - VNC_PASSWD=vncpassword
      - IS_SECURE=true
    depends_on:
      - novnc
    networks:
      - isolated1 # réseau isolé propre à ce xvnc

  xvnc2:
    build: ./ubuntu_icewm/
    environment:
      - USER=isen
      - VNC_PORT=5901
      - VNC_PASSWD=vncpassword
      - IS_SECURE=true
    depends_on:
      - novnc
    networks:
      - isolated2

  xvnc3:
    build: ./ubuntu_icewm/
    environment:
      - USER=isen
      - VNC_PORT=5902
      - VNC_PASSWD=vncpassword
      - IS_SECURE=true
    depends_on:
      - novnc
    networks:
      - isolated3

networks:
  isolated1:
    internal: true
  isolated2:
    internal: true
  isolated3:
    internal: true
  net:
    #external: true # à mettre si on n'arrive pas à communiquer avec NoVNC
