FROM ubuntu:20.04

ENV DISPLAY=:1 \
    VNC_PORT=5901 \
    NO_VNC_PORT=6901
EXPOSE $VNC_PORT $NO_VNC_PORT



### Envrionment config
ENV HOME=/headless \
    INST_SCRIPTS=/headless/install \
    NO_VNC_HOME=/headless/noVNC \
WORKDIR $HOME

### Add all install scripts for further steps
ADD ./scripts/ $INST_SCRIPTS/
RUN find $INST_SCRIPTS/
